from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
import os

OUTPUT = r"C:\Users\hariv\Downloads\PlagiaScan_Project_Explanation.pdf"

doc = SimpleDocTemplate(
    OUTPUT,
    pagesize=A4,
    topMargin=2*cm, bottomMargin=2*cm,
    leftMargin=2.2*cm, rightMargin=2.2*cm
)

W = A4[0] - 4.4*cm  # usable width

styles = getSampleStyleSheet()

# ── Custom Styles ──────────────────────────────────────────────────────────────
DARK   = colors.HexColor("#1a1a2e")
ACCENT = colors.HexColor("#7c3aed")
LIGHT  = colors.HexColor("#f5f3ff")
MID    = colors.HexColor("#ede9fe")
GRAY   = colors.HexColor("#6b7280")
CODE_BG= colors.HexColor("#f3f4f6")

def sty(name, **kw):
    s = ParagraphStyle(name, **kw)
    return s

H0 = sty("H0", fontName="Helvetica-Bold", fontSize=22, textColor=DARK,
          spaceAfter=4, spaceBefore=6, alignment=TA_CENTER)
H0sub = sty("H0sub", fontName="Helvetica", fontSize=11, textColor=GRAY,
            spaceAfter=14, alignment=TA_CENTER)
H1 = sty("H1", fontName="Helvetica-Bold", fontSize=14, textColor=ACCENT,
         spaceBefore=16, spaceAfter=4)
H2 = sty("H2", fontName="Helvetica-Bold", fontSize=11, textColor=DARK,
         spaceBefore=10, spaceAfter=3)
BODY = sty("BODY", fontName="Helvetica", fontSize=9.5, textColor=DARK,
           leading=14, alignment=TA_JUSTIFY, spaceAfter=4)
BULLET = sty("BULLET", fontName="Helvetica", fontSize=9.5, textColor=DARK,
             leading=13, leftIndent=14, bulletIndent=0, spaceAfter=2)
CODE = sty("CODE", fontName="Courier", fontSize=8.5, textColor=DARK,
           leading=12, leftIndent=10, spaceAfter=2)
PITCH = sty("PITCH", fontName="Helvetica-Oblique", fontSize=10,
            textColor=colors.HexColor("#4c1d95"), leading=14,
            leftIndent=10, spaceAfter=4)
LABEL= sty("LABEL", fontName="Helvetica-Bold", fontSize=9, textColor=ACCENT,
           spaceAfter=1)

def hr(): return HRFlowable(width="100%", thickness=1, color=MID, spaceAfter=6, spaceBefore=4)
def sp(n=6): return Spacer(1, n)

def h1(text): return Paragraph(text, H1)
def h2(text): return Paragraph(text, H2)
def body(text): return Paragraph(text, BODY)
def bullet(text): return Paragraph(f"• {text}", BULLET)
def code(text): return Paragraph(text, CODE)
def label(text): return Paragraph(text, LABEL)

def table(data, col_widths, header=True):
    t = Table(data, colWidths=col_widths, repeatRows=1 if header else 0)
    ts = [
        ("BACKGROUND", (0,0), (-1,0), ACCENT if header else MID),
        ("TEXTCOLOR",  (0,0), (-1,0), colors.white if header else DARK),
        ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE",   (0,0), (-1,-1), 8.5),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.white, LIGHT]),
        ("GRID", (0,0), (-1,-1), 0.4, colors.HexColor("#d1d5db")),
        ("LEFTPADDING",  (0,0), (-1,-1), 6),
        ("RIGHTPADDING", (0,0), (-1,-1), 6),
        ("TOPPADDING",   (0,0), (-1,-1), 4),
        ("BOTTOMPADDING",(0,0), (-1,-1), 4),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
    ]
    t.setStyle(TableStyle(ts))
    return t

# ══════════════════════════════════════════════════════════════════════════════
story = []

# ── COVER ─────────────────────────────────────────────────────────────────────
story += [
    sp(20),
    Paragraph("PlagiaScan", H0),
    Paragraph("AI-Powered Plagiarism & AI Content Detection Platform", H0sub),
    Paragraph("Complete Project Explanation — Placement Edition", H0sub),
    sp(10),
    hr(),
    sp(6),
]

# ── 1. OVERVIEW ───────────────────────────────────────────────────────────────
story += [h1("1. Project Overview"), hr()]
story += [
    body("PlagiaScan is a full-stack web application that performs two distinct tasks:"),
    bullet("<b>Plagiarism Detection</b> — Compares uploaded documents against a database using vector similarity search to find copied or paraphrased content."),
    bullet("<b>AI Content Detection</b> — Analyzes writing style using NLP heuristics to determine whether text was written by a human or generated by AI (ChatGPT, Gemini, etc.)."),
    sp(6),
    label("One-line Pitch for Interviews:"),
    Paragraph(
        '"PlagiaScan is a full-stack web app that uses Sentence Transformers and vector embeddings '
        'to detect plagiarism, and an NLP heuristic ensemble to identify AI-generated content — '
        'built with FastAPI, React, and Qdrant."',
        PITCH
    ),
]

# ── 2. TECH STACK ─────────────────────────────────────────────────────────────
story += [h1("2. Tech Stack"), hr()]

story += [h2("Frontend")]
story += [table(
    [["Tool", "Version", "Purpose"],
     ["React", "18.x", "UI framework — component-based SPA"],
     ["Vite", "7.x", "Build tool & dev server (faster than Webpack)"],
     ["Axios", "—", "HTTP client for REST API calls"],
     ["React Router", "—", "Client-side routing (Login, Dashboard, Report)"],
     ["Vanilla CSS", "—", "Custom styling — no framework overhead"]],
    [3.5*cm, 2*cm, 9.5*cm]
), sp(8)]

story += [h2("Backend")]
story += [table(
    [["Tool", "Version", "Purpose"],
     ["FastAPI", "0.104", "Python REST API — async, auto-generates Swagger docs"],
     ["Uvicorn", "0.24", "ASGI server to run FastAPI"],
     ["SQLAlchemy", "2.0", "ORM — maps Python classes to database tables"],
     ["SQLite", "—", "Local relational DB (users, documents, scans)"],
     ["Pydantic", "2.5", "Data validation and settings management"],
     ["Python-Jose", "—", "JWT token generation and verification"],
     ["Passlib + Bcrypt", "—", "Secure password hashing (industry standard)"]],
    [3.5*cm, 2*cm, 9.5*cm]
), sp(8)]

story += [h2("AI / ML")]
story += [table(
    [["Tool", "Purpose"],
     ["Sentence Transformers (all-MiniLM-L6-v2)", "Converts text chunks into 384-dim vector embeddings"],
     ["Qdrant (local file mode)", "Vector DB — cosine similarity search using HNSW indexing"],
     ["Datasketch (MinHash)", "Lexical fingerprinting — fast approximate deduplication"],
     ["Custom NLP Heuristics", "AI detection: burstiness, TTR, transition words, sentence length"]],
    [6*cm, 9*cm]
), sp(8)]

story += [h2("Cloud & Services")]
story += [table(
    [["Tool", "Purpose"],
     ["Fluxbase", "Cloud MySQL via REST API — production database"],
     ["Gmail SMTP (smtplib)", "Sends welcome emails on user registration"],
     ["python-docx", "Parses .docx Word files"],
     ["pypdf", "Parses .pdf files"],
     ["BeautifulSoup4", "Parses .html files"],
     ["mimetypes (stdlib)", "Detects file type from extension (Windows-safe)"]],
    [5*cm, 10*cm]
), sp(4)]

# ── 3. ARCHITECTURE ───────────────────────────────────────────────────────────
story += [h1("3. System Architecture"), hr()]
arch_data = [[
    Paragraph(
        """<font name="Courier" size="8">Browser (React + Vite)<br/>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| HTTP/REST (Axios)<br/>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;v<br/>
  FastAPI Backend (Uvicorn)<br/>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
  &nbsp;&nbsp;&nbsp;┌────┴───────────┐<br/>
  &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
  SQLite DB&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Qdrant VectorDB<br/>
  (Users,Docs,&nbsp;&nbsp;&nbsp;&nbsp;(384-dim cosine<br/>
  &nbsp;Scans)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;similarity search)<br/>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br/>
   Fluxbase (Cloud MySQL via REST)</font>""",
        CODE
    )
]]
arch_t = Table(arch_data, colWidths=[W])
arch_t.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,-1), CODE_BG),
    ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#d1d5db")),
    ("LEFTPADDING", (0,0), (-1,-1), 12),
    ("TOPPADDING", (0,0), (-1,-1), 10),
    ("BOTTOMPADDING", (0,0), (-1,-1), 10),
]))
story += [arch_t, sp(6)]

# ── 4. HOW FEATURES WORK ──────────────────────────────────────────────────────
story += [h1("4. Core Features — How They Work"), hr()]

story += [h2("4.1 User Authentication")]
story += [
    bullet("<b>Registration:</b> Email + password → bcrypt hash → stored in SQLite → background task sends welcome email via Gmail SMTP → JWT returned"),
    bullet("<b>Login:</b> Credentials verified → JWT (HS256) generated → stored in browser localStorage → attached as Authorization: Bearer header on all API requests"),
    bullet("<b>Route Protection:</b> FastAPI Depends(get_current_user) verifies JWT on every protected endpoint"),
]

story += [h2("4.2 Document Upload & Indexing Pipeline")]
story += [
    bullet("<b>Step 1:</b> File uploaded → saved to disk → SQLAlchemy creates Document record (status: pending)"),
    bullet("<b>Step 2:</b> FastAPI BackgroundTask triggered (non-blocking — HTTP response returned immediately)"),
    bullet("<b>Step 3:</b> Text extracted using the correct parser (PDF/DOCX/HTML/TXT)"),
    bullet("<b>Step 4:</b> Text cleaned, MinHash signature generated for lexical fingerprinting"),
    bullet("<b>Step 5:</b> Text split into ~200-word overlapping chunks by Chunker"),
    bullet("<b>Step 6:</b> Each chunk encoded into a 384-dim embedding vector using all-MiniLM-L6-v2"),
    bullet("<b>Step 7:</b> Vectors upserted into Qdrant with payload {document_id, chunk_index, text}"),
    bullet("<b>Step 8:</b> Document status updated to 'indexed'"),
]

story += [h2("4.3 Plagiarism Detection")]
story += [
    bullet("Each chunk of the target document is encoded into a vector"),
    bullet("Qdrant searches for the top-5 most similar vectors from OTHER documents (cosine similarity ≥ 0.65)"),
    bullet("Plagiarism Score = (matched_chunks / total_chunks) × 100%"),
    bullet("Semantic similarity means paraphrased text is caught — unlike keyword matching (TF-IDF)"),
    bullet("Frontend polls GET /api/v1/scans/{id} every 2 seconds to show live progress bar"),
]

story += [h2("4.4 AI Content Detection (5-Signal Heuristic Ensemble)")]
story += [
    table(
        [["Signal", "What it Measures", "AI Pattern"],
         ["Sentence Burstiness", "Std-dev / mean of sentence lengths", "Low variance — uniform sentences"],
         ["Type-Token Ratio (TTR)", "Unique words / total words", "Lower — repetitive vocabulary"],
         ["Transition Word Density", "'furthermore', 'moreover', 'consequently' etc.", "Much higher usage per 1000 words"],
         ["Avg Sentence Length", "Mean words per sentence", "Longer (18–28 words), complete sentences"],
         ["Informality Score", "Contractions + exclamations", "Almost zero in AI text"]],
        [3.5*cm, 5.5*cm, 6*cm]
    ), sp(4),
    body("Final score = weighted average of all 5 signals. Labeled as: 0–39% Likely Human | 40–59% Mixed | 60–79% Likely AI | 80–100% AI Generated"),
]

# ── 5. API ENDPOINTS ──────────────────────────────────────────────────────────
story += [h1("5. API Endpoints (RESTful Design)"), hr()]
story += [table(
    [["Method", "Endpoint", "Description"],
     ["POST", "/api/v1/auth/register", "Register new user (sends welcome email)"],
     ["POST", "/api/v1/auth/login", "Login — returns JWT token"],
     ["POST", "/api/v1/documents/", "Upload a document (PDF, DOCX, TXT, HTML)"],
     ["GET",  "/api/v1/documents/", "List all documents for current user"],
     ["GET",  "/api/v1/documents/{id}", "Get document details and status"],
     ["DELETE","/api/v1/documents/{id}","Delete document, vectors, and scan records"],
     ["POST", "/api/v1/scans/", "Initiate plagiarism + AI scan on a document"],
     ["GET",  "/api/v1/scans/{id}", "Get scan status, progress, and full report"],
     ["GET",  "/api/v1/scans/{id}/pdf", "Download scan report as PDF"],
     ["GET",  "/health", "Health check endpoint"]],
    [2*cm, 5.5*cm, 7.5*cm]
), sp(4)]

# ── 6. INTERVIEW Q&A ──────────────────────────────────────────────────────────
story += [h1("6. Key Interview Q&A"), hr()]

qas = [
    ("Why FastAPI over Django or Flask?",
     "FastAPI is async-native, auto-generates OpenAPI/Swagger docs, uses Python type hints for validation via Pydantic, and is significantly faster for I/O-bound tasks like file processing."),
    ("Why Sentence Transformers?",
     "all-MiniLM-L6-v2 is lightweight (80MB) but highly accurate. It maps semantically similar text to nearby vectors — paraphrased content is caught unlike keyword-matching approaches like TF-IDF or Jaccard similarity."),
    ("Why Qdrant?",
     "Qdrant uses HNSW indexing for efficient Approximate Nearest Neighbor (ANN) search. It runs locally in file-based mode requiring no server infrastructure for development."),
    ("How does plagiarism scoring work?",
     "Score = (matched_chunks / total_chunks) × 100. Each chunk is encoded and searched in Qdrant. If cosine similarity ≥ 0.65 is found against any chunk from a different document, it counts as a match."),
    ("Why heuristics instead of a transformer model for AI detection?",
     "The RoBERTa model required 1.4GB download and had a protobuf version conflict on Windows. The heuristic approach uses proven linguistic signals that run instantly offline with empirically verified accuracy."),
    ("How is JWT authentication implemented?",
     "Login returns a signed JWT (HS256) containing user ID and expiry. Frontend stores it in localStorage. All API requests attach it as 'Authorization: Bearer <token>'. FastAPI verifies it using python-jose on every protected route."),
]

for q, a in qas:
    story += [
        KeepTogether([
            Paragraph(f"Q: {q}", sty("QA_Q", fontName="Helvetica-Bold", fontSize=9.5,
                                      textColor=ACCENT, spaceBefore=8, spaceAfter=2)),
            Paragraph(f"A: {a}", sty("QA_A", fontName="Helvetica", fontSize=9.5,
                                      textColor=DARK, leading=13, leftIndent=12,
                                      spaceAfter=4)),
        ])
    ]

# ── 7. CHALLENGES SOLVED ──────────────────────────────────────────────────────
story += [h1("7. Challenges Solved"), hr()]
story += [table(
    [["Challenge", "Solution Applied"],
     ["Qdrant locks storage folder with concurrent requests", "Implemented a process-wide singleton for the Qdrant client"],
     ["python-magic requires native DLL on Windows", "Replaced with Python stdlib mimetypes module"],
     ["RoBERTa model fails due to protobuf conflict", "Built a 5-signal NLP heuristic ensemble as replacement"],
     ["Windows terminal rejects 0.0.0.0 host binding", "Changed to 127.0.0.1 binding for local Windows compatibility"],
     ["SQLite missing progress/current_step columns", "Applied ALTER TABLE migration at runtime on startup"],
     ["Unicode emoji crash Windows cp1252 terminal encoding", "Replaced all non-ASCII characters in print statements"]],
    [7*cm, 8*cm]
), sp(4)]

# ── 8. RESUME BULLETS ─────────────────────────────────────────────────────────
story += [h1("8. Resume Bullet Points"), hr()]
resume_bullets = [
    "Developed a full-stack plagiarism & AI content detection platform using <b>FastAPI</b>, <b>React</b>, and <b>Qdrant vector database</b>",
    "Implemented <b>semantic similarity search</b> using Sentence Transformers (all-MiniLM-L6-v2) with 384-dimensional cosine embeddings for cross-document plagiarism detection",
    "Built a <b>JWT-based authentication system</b> with bcrypt password hashing and token-protected API routes using FastAPI dependency injection",
    "Designed a <b>5-signal NLP heuristic ensemble</b> for AI content detection (burstiness, type-token ratio, transition word density, sentence length, informality) — works fully offline",
    "Integrated <b>Fluxbase cloud MySQL</b> database via REST API as production backend, with SQLite fallback for local development",
    "Implemented <b>async background task pipeline</b> using FastAPI BackgroundTasks for non-blocking document indexing and scan processing",
    "Connected <b>Gmail SMTP</b> for transactional welcome emails triggered on user registration",
    "Resolved production bugs: Qdrant file-lock concurrency on Windows, protobuf version conflicts, and terminal encoding crashes",
]
for b in resume_bullets:
    story.append(bullet(b))

story += [sp(10), hr(),
    Paragraph("Generated for placement preparation | PlagiaScan Project", 
              sty("Footer", fontName="Helvetica", fontSize=8, textColor=GRAY, alignment=TA_CENTER))
]

doc.build(story)
print(f"PDF saved to: {OUTPUT}")
