"""Add progress columns

Revision ID: 1712ce2ef7a6
Revises: 6ef86a767ece
Create Date: 2025-11-24 09:35:03.747136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1712ce2ef7a6'
down_revision: Union[str, None] = '6ef86a767ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('scans', sa.Column('current_step', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'current_step')
    op.drop_column('scans', 'progress')
    # ### end Alembic commands ###
