import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from app.core.config import settings

logger = logging.getLogger(__name__)

def send_welcome_email(to_email: str, full_name: str = None):
    """
    Send a welcome email to the user asynchronously using SMTP.
    Requires EMAIL_ADDRESS and EMAIL_PASSWORD in .env.
    """
    sender_email = settings.EMAIL_ADDRESS
    sender_password = settings.EMAIL_PASSWORD

    if not sender_email or not sender_password:
        logger.warning("Email credentials not configured. Skipping welcome email.")
        return

    name_str = full_name if full_name else "User"

    subject = "Welcome to PlagiaScan! ✨"
    body = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome to PlagiaScan</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #f3f4f6; font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale;">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: #f3f4f6; padding: 40px 0;">
            <tr>
                <td align="center">
                    <table border="0" cellpadding="0" cellspacing="0" width="600" style="background-color: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -2px rgba(0,0,0,0.05);">
                        <!-- Header with violet gradient -->
                        <tr>
                            <td align="center" style="background: linear-gradient(135deg, #7c3aed 0%, #4f46e5 100%); padding: 40px 20px; color: #ffffff;">
                                <div style="font-size: 32px; margin-bottom: 8px; font-weight: bold; letter-spacing: 1px;">✨ PlagiaScan</div>
                                <p style="margin: 0; font-size: 15px; color: #ede9fe; font-weight: 500; letter-spacing: 0.5px;">Advanced Plagiarism & AI Detection</p>
                            </td>
                        </tr>
                        <!-- Main Body Content -->
                        <tr>
                            <td style="padding: 40px 30px; color: #1e1b4b;">
                                <h2 style="margin-top: 0; margin-bottom: 16px; font-size: 22px; font-weight: 700; color: #1e1b4b;">Welcome aboard, {name_str}!</h2>
                                <p style="margin: 0 0 24px 0; font-size: 15px; line-height: 24px; color: #4b5563;">Thank you for registering with PlagiaScan. Your account has been successfully created and is ready to use. You now have full access to our state-of-the-art document analysis pipeline.</p>
                                
                                <!-- Key Features Grid -->
                                <div style="background-color: #f5f3ff; border-radius: 12px; padding: 24px; margin-bottom: 30px; border: 1px solid #e9d5ff;">
                                    <h3 style="margin-top: 0; margin-bottom: 16px; font-size: 14px; font-weight: 700; color: #7c3aed; text-transform: uppercase; letter-spacing: 0.5px;">What you can do next:</h3>
                                    
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                        <tr>
                                            <td valign="top" style="font-size: 20px; width: 30px; padding-bottom: 16px;">🔍</td>
                                            <td style="font-size: 14px; line-height: 20px; color: #4b5563; padding-bottom: 16px;">
                                                <strong style="color: #1e1b4b;">Plagiarism Scanning:</strong> Instantly check text similarity against internal and web resources using cosine vector embeddings.
                                            </td>
                                        </tr>
                                        <tr>
                                            <td valign="top" style="font-size: 20px; width: 30px; padding-bottom: 16px;">🧠</td>
                                            <td style="font-size: 14px; line-height: 20px; color: #4b5563; padding-bottom: 16px;">
                                                <strong style="color: #1e1b4b;">AI Content Verification:</strong> Utilize our 5-signal NLP heuristic ensemble to detect texts generated by ChatGPT or Gemini.
                                            </td>
                                        </tr>
                                        <tr>
                                            <td valign="top" style="font-size: 20px; width: 30px;">📄</td>
                                            <td style="font-size: 14px; line-height: 20px; color: #4b5563;">
                                                <strong style="color: #1e1b4b;">Multi-Format Support:</strong> Upload documents seamlessly in PDF, DOCX, HTML, or TXT formats.
                                            </td>
                                        </tr>
                                    </table>
                                </div>

                                <!-- CTA Button -->
                                <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                    <tr>
                                        <td align="center">
                                            <a href="https://plagiarism-scan-frontend.onrender.com" target="_blank" style="display: inline-block; background: linear-gradient(135deg, #7c3aed 0%, #4f46e5 100%); color: #ffffff; text-decoration: none; padding: 14px 32px; font-size: 15px; font-weight: 600; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(124, 58, 237, 0.3), 0 2px 4px -1px rgba(124, 58, 237, 0.15);">Go to Dashboard</a>
                                        </td>
                                    </tr>
                                </table>
                                
                                <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 30px 0 20px 0;">
                                
                                <p style="margin: 0; font-size: 13px; color: #9ca3af; line-height: 18px;">If you have any questions or need help setting up your workflow, feel free to reply directly to this email.</p>
                            </td>
                        </tr>
                        <!-- Footer -->
                        <tr>
                            <td align="center" style="background-color: #f9fafb; padding: 24px 20px; border-top: 1px solid #f3f4f6; color: #9ca3af; font-size: 12px; line-height: 16px;">
                                <p style="margin: 0 0 4px 0; font-weight: 600; color: #6b7280;">© 2026 PlagiaScan Inc.</p>
                                <p style="margin: 0;">Securing Academic & Professional Integrity.</p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </body>
    </html>
    """

    msg = MIMEMultipart()
    msg['From'] = f"PlagiaScan <{sender_email}>"
    msg['To'] = to_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'html'))

    try:
        # Connect to Gmail SMTP server
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        logger.info(f"Welcome email sent to {to_email}")
    except Exception as e:
        logger.error(f"Failed to send welcome email to {to_email}: {e}")
